# Generated by Django 4.1.4 on 2022-12-24 09:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("polls", "0005_comment_post"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="post",
            name="comments",
        ),
    ]
