# Generated by Django 4.1.4 on 2022-12-24 09:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("polls", "0006_remove_post_comments"),
    ]

    operations = [
        migrations.AddField(
            model_name="comment",
            name="post",
            field=models.ForeignKey(
                default=0, on_delete=django.db.models.deletion.CASCADE, to="polls.post"
            ),
        ),
    ]
